version: '3.6'

services:
  app:
    build:
      context: ../../
    image: microsnail-frontend:dev
    command: sh -c 'npm start & npm run watch'
    stdin_open: true  
    tty: true
    ports:
      - 33330:8080

    volumes:
      - ${WORKSPACE}/frontend:/app/
